# Generated by Django 4.2.4 on 2023-09-19 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeepermissionrelation",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="employeepermissionrelation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
