# Generated by Django 4.2.4 on 2023-09-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="employee",
            name="password",
            field=models.CharField(max_length=200),
        ),
    ]
