# Generated by Django 4.2.4 on 2023-09-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_employeepermissionrelation_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeerole",
            name="role",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="employeepermissionrelation",
            unique_together={("employee", "permission")},
        ),
    ]
